/**
 * Created by rraleigh on 2/13/18.
 */
import {Promotion} from './promotion';

export const PROMOS: Promotion[] = [
  {
    promoId: 15647,
    image: 'assets/images/66073.png',
    name: 'Certified Service ACDelco dexos1™ or Mobil 1™ Full Synthetic Oil Change Rebate',
    displayName: 'Certified Service ACDelco dexos1™ or Mobil 1™ Full Synthetic Oil Change Rebate',
    value: '$15 or Up to $30 with GM or BuyPower Card',
    startDate: new Date('5/01/2018'),
    endDate: new Date('6/30/2018'),
    expiryDate: new Date('7/31/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66073_rebate_form.pdf',
    offerCode: '66073',
    isOnline: true,
    requiresLastFourCard: true,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: true,
    validProducts: ['oil change'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 15649,
    image: 'assets/images/66074.png',
    name: 'Cabin Air Filter and Engine Air Filter Rebate',
    displayName: 'Cabin Air Filter and Engine Air Filter Rebate',
    value: '$10 /$20 or Up to $40 with GM or BuyPower Card',
    startDate: new Date('5/01/2018'),
    endDate: new Date('6/30/2018'),
    expiryDate: new Date('7/31/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66074_rebate_form.pdf',
    offerCode: '66074',
    isOnline: true,
    requiresLastFourCard: true,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: true,
    validProducts: ['air filter'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 15970,
    image: 'assets/images/66050.png',
    name: 'Powertrain ISC Private Bundle Rebate',
    displayName: 'Powertrain ISC Private Bundle Rebate',
    value: '$250',
    startDate: new Date('6/01/2018'),
    endDate: new Date('8/31/2018'),
    expiryDate: new Date('9/30/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66094_rebate_form.pdf',
    offerCode: '66094',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['engine', 'transmission', 'transfer case'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 15869,
    image: 'assets/images/66050.png',
    name: 'Powertrain ISC Private Rebate',
    displayName: 'Powertrain ISC Private Rebate',
    value: '$200',
    startDate: new Date('6/01/2018'),
    endDate: new Date('8/31/2018'),
    expiryDate: new Date('9/30/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66081_rebate_form.pdf',
    offerCode: '66081',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['engine', 'transmission', 'transfer case'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 15764,
    image: 'assets/images/66080.png',
    name: 'Christian Brothers Texas Private Rebate',
    displayName: 'Christian Brothers Texas Private Rebate',
    value: '$200',
    startDate: new Date('6/01/2018'),
    endDate: new Date('8/31/2018'),
    expiryDate: new Date('9/30/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66080_rebate_form.pdf',
    offerCode: '66080',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['engine'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  }, {
    promoId: 15654,
    image: 'assets/images/66077.png',
    name: 'Chevrolet Performance for Gen 5 and Gen 6 Camaro Parts Rebate',
    displayName: 'Chevrolet Performance for Gen 5 and Gen 6 Camaro Parts Rebate',
    value: '$25/$50/$100',
    startDate: new Date('6/01/2018'),
    endDate: new Date('6/30/2018'),
    expiryDate: new Date('7/31/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66077_rebate_form.pdf',
    offerCode: '66077',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: true,
    validProducts: ['accessory parts'],
    validLocationType: ['dealer', 'other'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 15646,
    image: 'assets/images/66074.png',
    name: 'Cabin Air Filter and Engine Air Filter Rebate',
    displayName: 'Cabin Air Filter and Engine Air Filter Rebate',
    value: '$10 /$20 or Up to $40 with GM or BuyPower Card',
    startDate: new Date('5/01/2018'),
    endDate: new Date('6/30/2018'),
    expiryDate: new Date('7/31/2018'),
    type: 'airFilter',
    pdfLink: 'assets/PDFs/66079_rebate_form.pdf',
    offerCode: '66079',
    isOnline: true,
    requiresLastFourCard: true,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['air filter'],
    validLocationType: [],
    fleetOffer: true,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 15645,
    image: 'assets/images/66073.png',
    name: 'Certified Service Private Oil Rebate',
    displayName: 'Certified Service Private Oil Rebate',
    value: '$15 or Up to $30 with GM or BuyPower Card',
    startDate: new Date('5/01/2018'),
    endDate: new Date('6/30/2018'),
    expiryDate: new Date('7/31/2018'),
    type: 'oilChange',
    pdfLink: 'assets/PDFs/66078_rebate_form.pdf',
    offerCode: '66078',
    isOnline: true,
    requiresLastFourCard: true,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['oil change'],
    validLocationType: [],
    fleetOffer: true,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 15429,
    image: 'assets/images/66076.png',
    name: 'Components Private Rebate Offer',
    displayName: 'Components Private Rebate Offer',
    value: '$50',
    startDate: new Date('5/01/2018'),
    endDate: new Date('7/31/2018'),
    expiryDate: new Date('8/31/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66076_rebate_form.pdf',
    offerCode: '66076',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: true,
    validProducts: ['transmission parts'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  // {
  //     promoId: 15428,
  //     image: 'assets/images/66075.jpg',
  //     name: 'Chevrolet Performance Front-End Accessory Drive Rebate',
  //     displayName: 'Chevrolet Performance Front-End Accessory Drive Rebate',
  //     value: '$50/$100',
  //     startDate: new Date('4/15/2018'),
  //     endDate: new Date('5/31/2018'),
  //     expiryDate: new Date('6/30/2018'),
  //     type: 'engine',
  //     pdfLink: 'assets/PDFs/66075_rebate_form.pdf',
  //     offerCode: '66075',
  //     isOnline: true,
  //     requiresLastFourCard: false,
  //     hasPromoSpecificRetailers: false,
  //     captureDealer: true,
  //     hasVirtualCardOption: true,
  //     validProducts: ['engine parts'],
  //     validLocationType: ['dealer', 'other'],
  //     fleetOffer: false,
  //     captureImage: true,
  //     captureTransmissionType: false,
  //     tileDisclaimer: ""
  // },
  {
    promoId: 15080,
    image: 'assets/images/66072.png',
    name: 'Chevrolet Performance Diesel Block Engine Rebate',
    displayName: 'Chevrolet Performance Diesel Block Engine Rebate',
    value: '$100',
    startDate: new Date('4/1/2018'),
    endDate: new Date('4/30/2018'),
    expiryDate: new Date('5/31/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66072_rebate_form.pdf',
    offerCode: '66072',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: true,
    validProducts: ['engine parts', 'engine'],
    validLocationType: ['dealer', 'other'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 15078,
    image: 'assets/images/66071.png',
    name: 'GM Certified Service Powertrain Rebate Offer',
    displayName: 'GM Certified Service Powertrain Rebate Offer',
    value: '$200',
    startDate: new Date('4/1/2018'),
    endDate: new Date('12/31/2018'),
    expiryDate: new Date('1/31/2019'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66071_rebate_form.pdf',
    offerCode: '66071',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: true,
    validProducts: ['transmission', 'engine'],
    validLocationType: ['dealer', 'other'],
    fleetOffer: false,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 15077,
    image: 'assets/images/66070.png',
    name: 'Genuine GM GMT800 Transfer Case Rebate',
    displayName: 'Genuine GM GMT800 Transfer Case Rebate',
    value: '$150',
    startDate: new Date('4/1/2018'),
    endDate: new Date('6/30/2018'),
    expiryDate: new Date('7/31/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66070_rebate_form.pdf',
    offerCode: '66070',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: true,
    validProducts: ['transfer case'],
    validLocationType: ['dealer', 'other'],
    fleetOffer: false,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 15076,
    image: 'assets/images/66067.png',
    name: 'Chevrolet Performance Shift Into Summer Rebate ',
    displayName: 'Chevrolet Performance Shift Into Summer Rebate ',
    value: '$50/$200',
    startDate: new Date('4/1/2018'),
    endDate: new Date('6/30/2018'),
    expiryDate: new Date('7/31/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66067_rebate_form.pdf',
    offerCode: '66067',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: true,
    validProducts: ['transmission'],
    validLocationType: ['dealer', 'other'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 14757,
    image: 'assets/images/mycs-rebates-offer-tile-tire.png',
    name: 'Certified Service Tire Rebate',
    displayName: 'Certified Service Tire Rebate',
    value: 'Up to $100 or $200 with GM or BuyPower Card',
    startDate: new Date('3/01/2018'),
    endDate: new Date('4/30/2018'),
    expiryDate: new Date('5/31/2018'),
    type: 'tires',
    pdfLink: 'assets/PDFs/66068_rebate_form.pdf',
    offerCode: '66068',
    isOnline: true,
    requiresLastFourCard: true,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['tires & tire pressure monitoring system'],
    validLocationType: [],
    fleetOffer: true,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: '*Up to $200 with GM or BuyPower Card'
  },
  {
    promoId: 14759,
    image: 'assets/images/tpms.png',
    name: 'Tire Pressure Monitoring System Rebate',
    displayName: 'Tire Pressure Monitoring System Rebate',
    value: '$10 or $20 with GM or BuyPower Card',
    startDate: new Date('3/01/2018'),
    endDate: new Date('4/30/2018'),
    expiryDate: new Date('5/31/2019'),
    type: 'tires',
    pdfLink: 'assets/PDFs/66069_rebate_form.pdf',
    offerCode: '66069',
    isOnline: true,
    requiresLastFourCard: true,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['tires & tire pressure monitoring system'],
    validLocationType: [],
    fleetOffer: true,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: '*$20 rebate with GM or BuyPower Card'
  },
  {
    promoId: 14758,
    image: 'assets/images/tpms.png',
    name: 'Certified Service Tire Pressure Monitoring System Rebate',
    displayName: 'Tire Pressure Monitoring System Rebate',
    value: 'Up to $10 or $20 with GM or BuyPower Card',
    startDate: new Date('3/01/2018'),
    endDate: new Date('4/30/2018'),
    expiryDate: new Date('5/31/2018'),
    type: 'tires',
    pdfLink: 'assets/PDFs/66066_rebate_form.pdf',
    offerCode: '66066',
    isOnline: true,
    requiresLastFourCard: true,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: true,
    validProducts: ['tires & tire pressure monitoring system'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: '*$20 with GM or BuyPower Card'
  },
  {
    promoId: 14756,
    image: 'assets/images/mycs-rebates-offer-tile-tire.png',
    name: 'Certified Service Tire Rebate',
    displayName: 'Certified Service Tire Rebate',
    value: 'Up to $100 or $200 with GM or BuyPower Card',
    startDate: new Date('3/01/2018'),
    endDate: new Date('4/30/2018'),
    expiryDate: new Date('5/31/2018'),
    type: 'tires',
    pdfLink: 'assets/PDFs/66065_rebate_form.pdf',
    offerCode: '66065',
    isOnline: true,
    requiresLastFourCard: true,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: true,
    validProducts: ['tires & tire pressure monitoring system'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: '*Up to $200 with GM or BuyPower Card'
  }, {
    promoId: 14088,
    image: 'assets/images/engine_parts.png',
    name: 'Powertrain Assembly and Parts Bundle ISC Private Rebate',
    displayName: 'Powertrain Assembly and Parts Bundle ISC Private Rebate',
    value: '$250',
    startDate: new Date('01/01/2018'),
    endDate: new Date('03/31/2018'),
    expiryDate: new Date('04/30/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66056_rebate_form.pdf',
    offerCode: '66056',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['engine', 'transmission', 'transfer case'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 14090,
    image: 'assets/images/66057.png',
    name: 'Chevrolet Performance Blocks and Heads Rebate',
    displayName: 'Chevrolet Performance Blocks and Heads Rebate',
    value: '$100',
    startDate: new Date('01/01/2018'),
    endDate: new Date('03/31/2018'),
    expiryDate: new Date('04/30/2018'),
    type: 'engineParts',
    pdfLink: 'assets/PDFs/66057_rebate_form.pdf',
    offerCode: '66057',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['engine parts'],
    validLocationType: ['dealer', 'other'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 14092,
    image: 'assets/images/mycs-rebates-offer-tile-sparkplug.png',
    name: 'ACDelco Spark Plug Rebate',
    displayName: 'ACDelco Spark Plug Rebate',
    value: 'Up to $48 or $96 with GM or BuyPower Card',
    startDate: new Date('01/01/2018'),
    endDate: new Date('12/31/2018'),
    expiryDate: new Date('01/31/2019'),
    type: 'sparkPlug',
    pdfLink: 'assets/PDFs/66055_rebate_form.pdf',
    offerCode: '66055',
    isOnline: true,
    requiresLastFourCard: true,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['spark plugs'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: false,
    captureTransmissionType: false,
    tileDisclaimer: '*Up to $96 with GM or BuyPower Card'

  },
  {
    promoId: 14079,
    image: 'assets/images/engine_parts.png',
    name: 'Powertrain Assembly and Parts Bundle ISC Private Rebate',
    displayName: 'Powertrain Assembly and Parts Bundle ISC Private Rebate',
    value: '$50',
    startDate: new Date('01/01/2018'),
    endDate: new Date('03/31/2018'),
    expiryDate: new Date('04/30/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66051_rebate_form.pdf',
    offerCode: '66051',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['engine', 'transmission', 'transfer case'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 14078,
    image: 'assets/images/66050.png',
    name: 'Powertrain ISC Private Rebate',
    displayName: 'Powertrain ISC Private Rebate',
    value: '$200',
    startDate: new Date('01/01/2018'),
    endDate: new Date('03/31/2018'),
    expiryDate: new Date('04/30/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66050_rebate_form.pdf',
    offerCode: '66050',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['engine', 'transmission', 'transfer case'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 14080,
    image: 'assets/images/66049.png',
    name: 'Engine & Transmission Rebate',
    displayName: 'Engine & Transmission Rebate',
    value: '$200',
    startDate: new Date('01/01/2018'),
    endDate: new Date('3/31/2018'),
    expiryDate: new Date('4/30/2018'),
    type: 'engine',
    pdfLink: 'assets/PDFs/66049_rebate_form.pdf',
    offerCode: '66049',
    isOnline: true,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['engine', 'transmission'],
    validLocationType: ['dealer'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: false,
    tileDisclaimer: ''
  },
  {
    promoId: 14081,
    image: 'assets/images/66040.png',
    name: 'Connect & Cruise Powertrain Rebate',
    displayName: 'Connect & Cruise Powertrain Rebate',
    value: '$500/$750',
    startDate: new Date('01/01/2018'),
    endDate: new Date('12/31/2018'),
    expiryDate: new Date('1/31/2019'),
    type: 'sparkPlug',
    pdfLink: 'assets/PDFs/66040_rebate_form.pdf',
    offerCode: '66040',
    isOnline: false,
    requiresLastFourCard: false,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['connect & cruise kit'],
    validLocationType: ['dealer', 'other'],
    fleetOffer: false,
    captureImage: true,
    captureTransmissionType: true,
    tileDisclaimer: ''
  },
  {
    promoId: 14092,
    image: 'assets/images/mycs-rebates-offer-tile-sparkplug.png',
    name: 'ACDelco Spark Plug Rebate',
    displayName: 'ACDelco Spark Plug Rebate',
    value: 'Up to $48 or $96 with GM or BuyPower Card',
    startDate: new Date('01/01/2018'),
    endDate: new Date('12/31/2018'),
    expiryDate: new Date('01/31/2019'),
    type: 'sparkPlug',
    pdfLink: 'assets/PDFs/66060_rebate_form.pdf',
    offerCode: '66060',
    isOnline: true,
    requiresLastFourCard: true,
    hasPromoSpecificRetailers: false,
    captureDealer: true,
    hasVirtualCardOption: false,
    validProducts: ['spark plugs'],
    validLocationType: [],
    fleetOffer: true,
    captureImage: null,
    captureTransmissionType: false,
    tileDisclaimer: '*Up to $96 with GM or BuyPower Card'
  }
];
